Repository oracle/graal, pull requests merged in 2018-03, with the labels that each got.

#312 JDK-8193241: Part 1. Added intrinsic support for (Math) dec/incrementExact
  compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/StandardGraphBuilderPlugins.java
Labels: accept, oracle-emp

#320 Add AArch64 support() function for determining CPUFeature support.
  compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
Labels: oca-signed

#325 AArch64: Put AArch64ReadReplacementPhase right before SchedulePhase.
  compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotSuitesProvider.java
  compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64ReadReplacementPhase.java
Labels: oracle-emp
