Repository oracle/graal, pull requests merged in 2019-08, with the labels that each got.

#1542 Fixes #1524 - Replace ForkJoinPool.commonPool() on static heap with d…
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/concurrent/DeferredCommonPool.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/concurrent/ForkJoinPoolFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/DisallowedImageHeapObjectFeature.java
Labels: oca-signed

#1586 Allow Array.set(objArray, index, null) to not throw NPE.
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaLangReflectSubstitutions.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ArraySetTest.java
Labels: bug, oca-signed

#1580 Add link to ReportingPolymorphism.md [ci skip]
  truffle/src/com.oracle.truffle.api.dsl/src/com/oracle/truffle/api/dsl/ReportPolymorphism.java
Labels: oca-signed

#1583 Add a try/finally to ensure the dir stream gets closed.
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaIOSubstitutions.java
Labels: native-image, oca-signed

#1595 Simplify SLReadLocalVariableNode
  truffle/src/com.oracle.truffle.sl/src/com/oracle/truffle/sl/nodes/local/SLReadLocalVariableNode.java
Labels: oca-signed

#1597 Sort TruffleTraceSplittingSummary by value
  compiler/src/org.graalvm.compiler.truffle.runtime/src/org/graalvm/compiler/truffle/runtime/TruffleSplittingStrategy.java
Labels: oca-signed

#1570 Remove not-implemented throw from ForkJoinTask.
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/RecomputedFields.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ForkJoinTest.java
Labels: native-image, oca-signed

#1633 Allow to stop building after the relocatable object file is written.
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageOptions.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeBootImageViaCC.java
Labels: oca-signed

#1638 Update sulong dynamic dependency
  vm/README.md
Labels: oca-signed
