Repository oracle/graal, pull requests merged in 2019-05, with the labels that each got.

#1176 Add conversion of null to/from zero for aarch64.
  compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
  substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/code/aarch64/SubstrateAArch64Backend.java
Labels: compiler, oca-signed

#821 Add note about macOS SDK headers for LLVM
  sulong/README.md
Labels: oca-signed

#1175 Refactor additional architecture-specific CPU feature manipulation.
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/CPUFeatureAccess.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/aarch64/AArch64CPUFeatureAccess.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/amd64/AMD64CPUFeatureAccess.java
  substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/SubstrateGraalUtils.java
Labels: oca-signed, substrate

#743 Consult sched_getaffinity in Linux-specific substitution for more accurate CPU count
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaLangSubstitutions.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/linux/LinuxSched.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxSubstitutions.java
Labels: oca-signed, substrate

#1219 MachO Objectfile for AArch64
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/macho/MachOCpuType.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/macho/MachOObjectFile.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/macho/MachORelocationElement.java
Labels: oca-signed

#1171 Float, Double Scalar FMA intrinsics
  compiler/src/org.graalvm.compiler.asm.amd64/src/org/graalvm/compiler/asm/amd64/AMD64Assembler.java
  compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64ArithmeticLIRGenerator.java
  compiler/src/org.graalvm.compiler.graph/src/org/graalvm/compiler/graph/spi/Canonicalizable.java
  compiler/src/org.graalvm.compiler.hotspot.amd64/src/org/graalvm/compiler/hotspot/amd64/AMD64HotSpotBackendFactory.java
  compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CheckGraalIntrinsics.java
  compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
  compiler/src/org.graalvm.compiler.lir.amd64/src/org/graalvm/compiler/lir/amd64/AMD64Ternary.java
  compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/gen/ArithmeticLIRGeneratorTool.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/TernaryNode.java
  compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64GraphBuilderPlugins.java
  compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/nodes/FusedMultiplyAddNode.java
Labels: oca-signed

#1264 add simple implementation for JVM_GetNanoTimeAdjustment()
  substratevm/src/com.oracle.svm.native.jvm.posix/src/JvmFuncs.c
Labels: oca-signed

#1220 Add support for calling-convention and deopt on AArch64 SVM.
  substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/code/aarch64/SubstrateAArch64Backend.java
  substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/code/aarch64/SubstrateAArch64RegisterConfig.java
Labels: compiler, oca-signed, substrate

#1298 Fix missing source position issue.
  compiler/src/org.graalvm.compiler.virtual/src/org/graalvm/compiler/virtual/phases/ea/GraphEffectList.java
Labels: oca-signed

#1284 add inputConsumed and outputConsumed field for JNI access.
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaIOSubstitutions.java
Labels: oca-signed

#1280 Provide definitions for JVM_Module functions.
  substratevm/src/com.oracle.svm.native.jvm.posix/src/JvmFuncs.c
Labels: oca-signed

#1282 set the contextClassLoader of this thread to be the System Classloader.
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/JavaThreads.java
Labels: oca-signed

#1300 Add objectFieldOffset method for Class, name pair
  substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/target/Target_jdk_internal_misc_Unsafe_Reflection.java
Labels: oca-signed, oracle-emp

#1318 Allow os.name and os.arch to be set when cross-compiling
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SystemPropertiesSupport.java
Labels: oca-signed

#1181 AArch64: Add MatchRules for bit field operations
  compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64BitFieldTest.java
  compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
  compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64BitFieldOp.java
Labels: accept, compiler, oca-signed

#1311 Cleanup on aisle aarch64.
  compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
  compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
  substratevm/src/com.oracle.svm.core.graal/src/com/oracle/svm/core/graal/code/aarch64/AArch64CGlobalDataLoadAddressOp.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/code/aarch64/SingleInstructionHostedPatcher.java
Labels: accept, native-image, oca-signed

#1343 AArch64: Supply scratch register on move reg2stack
  compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64Move.java
Labels: oracle-emp

#1325 Track constantReason for VMConstants along with JavaConstants.
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageCodeCache.java
Labels: oca-signed

#1326 No-op module reflection modifications.
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_lang_Module.java
Labels: oca-signed
