Repository oracle/graal, pull requests merged in 2019-11, with the labels that each got.

#1795 Generate complete stack trace string
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ConfigurableClassInitialization.java
Labels: oca-signed

#1747 AArch64: Elide L2I for binary and unary operations.
  compiler/src/org.graalvm.compiler.core.aarch64.test/src/org/graalvm/compiler/core/aarch64/test/AArch64ElideL2ITest.java
  compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64NodeMatchRules.java
Labels: compiler, oca-signed, oracle-emp, performance

#1799 Implement .p2align as a no-op
  sulong/projects/com.oracle.truffle.llvm.asm.amd64/src/com/oracle/truffle/llvm/asm/amd64/InlineAssembly.g4
  sulong/projects/com.oracle.truffle.llvm.asm.amd64/src/com/oracle/truffle/llvm/asm/amd64/InlineAssemblyLexer.java
  sulong/projects/com.oracle.truffle.llvm.asm.amd64/src/com/oracle/truffle/llvm/asm/amd64/InlineAssemblyParser.java
  sulong/tests/inlineassemblytests/p2align.c
Labels: oca-signed

#1819 Introduce ability to specify which timezones to include in the native imagee…
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/TimeZoneSubstitutions.java
Labels: oca-signed

#1824 AArch64: Fixed a bug in reading return address.
  substratevm/src/com.oracle.svm.core.graal.aarch64/src/com/oracle/svm/core/graal/aarch64/SubstrateAArch64Backend.java
Labels: compiler, native-image, oca-signed

#1854 Fix the error message in DisallowedImageHeapObjectFeature to refer to initialize-at-run-time instead of initialize-at-build-time
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/DisallowedImageHeapObjectFeature.java
Labels: oca-signed

#1856 Fix the com.oracle.svm.test.ForkJoinTest
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ForkJoinTest.java
Labels: oca-signed

#1897 Fix occurrences of occure*
  compiler/docs/Truffle.md
  compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CompilationWrapperTest.java
  sdk/src/org.graalvm.launcher/src/org/graalvm/launcher/MultiLanguageShell.java
  sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/Feature.java
  sdk/src/org.graalvm.polyglot/src/org/graalvm/polyglot/Source.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/ProcFSSupport.java
  truffle/src/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/PolymorphicTest.java
  truffle/src/com.oracle.truffle.api.dsl.test/src/com/oracle/truffle/api/dsl/test/TestHelper.java
  truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/source/Source.java
  vm/src/org.graalvm.component.installer/src/org/graalvm/component/installer/Bundle.properties
Labels: oca-signed

#1893 Prevent NullPointerException in SecurityServicesFeature
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/SecurityServiceTest.java
Labels: oca-signed
