Repository oracle/graal, pull requests merged in 2019-06, with the labels that each got.

#1352 Fix condition for memory bulk zeroing
  compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/replacements/NewObjectSnippets.java
Labels: oca-signed

#1365 fix openjdk8 download in Travis
  .travis.yml
Labels: oracle-emp

#1359 AArch64 - Read return address correctly.
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/aarch64/AArch64FrameAccess.java
Labels: native-image, oca-signed

#1377 Fix for #1338 - UnknownHostException when network down on OSX
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNetSubstitutions.java
Labels: native-image, oca-signed

#1355 Fix rounding conditions for SignedDivNode when canonicalized.
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/SignedDivNode.java
Labels: oca-signed

#1395 Fix travis config.
  .travis.yml
Labels: oracle-emp

#1391 Parallelized build for the LLVM backend
  substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMNativeImageCodeCache.java
  substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMOptions.java
Labels: oracle-emp

#1371 Avoid NPE when parsing static initializers.
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/graphbuilderconf/GraphBuilderConfiguration.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/phases/SharedGraphBuilderPhase.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/UnsafeAutomaticSubstitutionProcessor.java
Labels: native-image, oca-signed

#1381 Add `InnocuousThread` to the warning whitelist.
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/UnsafeAutomaticSubstitutionProcessor.java
Labels: oca-signed

#1411 #1274 Implement JVM_GetNanoTimeAdjustment
  substratevm/src/com.oracle.svm.native.jvm.posix/src/JvmFuncs.c
Labels: native-image

#1414 Java 11: Add java.io.UnixFileSystem.getNameMax0 implementation
  substratevm/src/com.oracle.svm.core.posix.jdk11/src/com/oracle/svm/core/posix/Target_java_io_UnixFileSystem.java
Labels: native-image, oca-signed
