Repository oracle/graal, pull requests merged in 2019-07, with the labels that each got.

#1455 switch to openjdk11 for Travis
  .travis.yml
Labels: oracle-emp

#1437 [native-image][JDK11] Fix error in JavaUtilZipSubstitutions.doInflate
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/JavaUtilZipSubstitutions.java
Labels: oca-signed

#1442 Fix CodeGenTest issue for AArch64
  compiler/src/org.graalvm.compiler.asm.aarch64.test/src/org/graalvm/compiler/asm/aarch64/test/AArch64BitCountAssemblerTest.java
  compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotBackend.java
Labels: accept, bug, compiler, oca-signed

#1482 Fixes #1481 - Implementation of SocketCleanable#cleanupClose0(...)
  substratevm/src/com.oracle.svm.core.posix.jdk11/src/com/oracle/svm/core/posix/jdk11/Target_java_net_SocketCleanable.java
Labels: native-image, oca-signed

#1493 Fixes #1491 - MacOSXSocketOptions implementations
  substratevm/src/com.oracle.svm.core.posix.jdk11/src/com/oracle/svm/core/posix/jdk11/darwin/Target_jdk_net_MacOSXSocketOptions.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/NetinetTcp.java
Labels: native-image, oca-signed

#1501 Add EPoll support under Java 11
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNIOSubstitutions.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxNIOSubstitutions.java
Labels: native-image, oca-signed

#1511 Emit a single STORE_STORE barrier for allocations
  compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/replacements/NewObjectSnippets.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/java/AbstractNewObjectNode.java
  compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/DefaultJavaLoweringProvider.java
Labels: oracle-emp

#1532 JDK 11 has different fields than JDK 8
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDKLibZipSubstitutions.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JNIRegistrationJavaNet.java
Labels: oca-signed

#1525 Fixes #1522 -- Add NetworkInterface.isUp0()
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNetSubstitutions.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/NetIf.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/NetworkInterfaceTest.java
Labels: native-image, oca-signed

#1552 Add more packages to satisfy ReflectionUtils warning.
  substratevm/mx.substratevm/mx_substratevm.py
Labels: native-image, oca-signed
