Repository oracle/graal, pull requests merged in 2020-10, with the labels that each got.

#2059 Field java.net.URL.handlers is deleted but still reachable
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaNetSubstitutions.java
Labels: native-image, oca-signed

#2673 native-image - Register String.getBytes() for JNI access at runtime
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationJava.java
Labels: oca-signed

#2895 [GR-26475] Remove obsolete hosted option RuntimeAssertionsFilter.
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/RuntimeAssertionsSupport.java
Labels: oracle-emp

#2588 Add intrinsics for floating point Math.min/Math.max on AArch64
  compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
  compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64ArithmeticLIRGenerator.java
  compiler/src/org.graalvm.compiler.core.common/src/org/graalvm/compiler/core/common/type/ArithmeticOpTable.java
  compiler/src/org.graalvm.compiler.core.common/src/org/graalvm/compiler/core/common/type/FloatStamp.java
  compiler/src/org.graalvm.compiler.core.common/src/org/graalvm/compiler/core/common/type/IntegerStamp.java
  compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/ReassociateAndCanonicalTest.java
  compiler/src/org.graalvm.compiler.hotspot.test/src/org/graalvm/compiler/hotspot/test/CheckGraalIntrinsics.java
  compiler/src/org.graalvm.compiler.jtt/src/org/graalvm/compiler/jtt/lang/Math_minMax.java
  compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArithmeticOp.java
  compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/gen/ArithmeticLIRGeneratorTool.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/BinaryArithmeticNode.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/MaxNode.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/MinMaxNode.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/calc/MinNode.java
  compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
Labels: oca-signed
