Repository oracle/graal, pull requests merged in 2020-07, with the labels that each got.

#2631 Fix the documentation in PolyglotNativeAPI
  substratevm/src/org.graalvm.polyglot.nativeapi/src/org/graalvm/polyglot/nativeapi/PolyglotNativeAPI.java
Labels: oca-signed

#2651 Reads around unsafe volatile read should not be commoned
  compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/VolatileAccessReadEliminationTest.java
  compiler/src/org.graalvm.compiler.virtual/src/org/graalvm/compiler/virtual/phases/ea/PEReadEliminationClosure.java
Labels: oca-signed

#2659 Test debuginfo on JDK 11 on both arm64 and amd64
  .travis.yml
Labels: oca-signed

#2661 Add compilation directory to debug info
  substratevm/DEBUGINFO.md
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FileEntry.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
Labels: oca-signed

#2681 Use correct starting point when doing CHA analysis for interfaces calls
  compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/SingleImplementorInterfaceTest.java
  compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/inlining/InliningTest.java
  compiler/src/org.graalvm.compiler.java/src/org/graalvm/compiler/java/BytecodeParser.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/CallTargetNode.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/java/MethodCallTargetNode.java
  compiler/src/org.graalvm.compiler.phases.common/src/org/graalvm/compiler/phases/common/inlining/walker/InliningData.java
  compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/PEGraphDecoderTest.java
  compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/classfile/ClassfileConstantPool.java
  compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/classfile/ConstantPoolPatch.java
  compiler/src/org.graalvm.compiler.serviceprovider.jdk11/src/org/graalvm/compiler/serviceprovider/GraalServices.java
  compiler/src/org.graalvm.compiler.serviceprovider.jdk13/src/org/graalvm/compiler/serviceprovider/GraalServices.java
  compiler/src/org.graalvm.compiler.serviceprovider.jdk8/src/org/graalvm/compiler/serviceprovider/GraalServices.java
  compiler/src/org.graalvm.compiler.serviceprovider/src/org/graalvm/compiler/serviceprovider/GraalServices.java
  compiler/src/org.graalvm.compiler.truffle.test/src/org/graalvm/compiler/truffle/test/PerformanceWarningTest.java
  substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/infrastructure/ConstantPoolPatch.java
  substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/infrastructure/WrappedConstantPool.java
Labels: oracle-emp

#2690 Add API to access classpath
  sdk/src/org.graalvm.nativeimage/snapshot.sigtest
  sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/Feature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/FeatureImpl.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ImageClassLoader.java
Labels: oracle-emp

#2698 Omit stmt_list from CU info record when it has no associated line records
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
Labels: oca-signed

#2682 UnsafeSubstitutionsTest stores object to int field
  compiler/src/org.graalvm.compiler.replacements.test/src/org/graalvm/compiler/replacements/test/UnsafeSubstitutionsTest.java
Labels: oca-signed

#2638 Make sure SSL logging (configured using javax.net.debug) works in native application
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java
Labels: oca-signed

#2606 SVM: Ignore directories when searching for default GCC
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CCompilerInvoker.java
Labels: oca-signed

#2699 Refactor NativeImageClassLoader and ImageClassLoader for Module support
  compiler/mx.compiler/mx_compiler.py
  substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
  substratevm/src/com.oracle.svm.hosted.jdk11/src/com/oracle/svm/hosted/NativeImageClassLoaderSupport.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/AbstractNativeImageClassLoaderSupport.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ClassLoaderFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/FallbackFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/FeatureImpl.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ImageBuildTask.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ImageClassLoader.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageClassLoader.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageClassLoaderSupport.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageSystemClassLoader.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SVMHost.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/agent/ClassInitializationTrackingVisitor.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/agent/jdk8/lambda/LambdaMetaFactoryRewriteVisitor.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/server/NativeImageBuildServer.java
  substratevm/src/com.oracle.svm.util.jdk11/src/com/oracle/svm/util/ModuleSupport.java
  substratevm/src/com.oracle.svm.util/src/com/oracle/svm/util/ModuleSupport.java
Labels: oracle-emp

#2714 Disable card marking temporarily to unblock CI.
  substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapOptions.java
Labels: bug, native-image, oracle-emp

#2718 Ensure custom_args are passed after all other args
  substratevm/mx.substratevm/rebuild-images.cmd
  substratevm/mx.substratevm/rebuild-images.sh
Labels: oracle-emp

#2649 Add intrinsics for get/put unsafe unaligned methods on AArch64
  compiler/src/org.graalvm.compiler.replacements.aarch64/src/org/graalvm/compiler/replacements/aarch64/AArch64GraphBuilderPlugins.java
  compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64GraphBuilderPlugins.java
Labels: oca-signed

#2695 Enforce consistent lookup of class and file names
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
Labels: oca-signed
