Repository oracle/graal, pull requests merged in 2020-08, with the labels that each got.

#2646 Keep image zone rules cache separate #2637
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_java_time_zone_ZoneRules.java
Labels: oca-signed

#2700 Fixes inlined code's cache paths for DWARF generation
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/mx.substratevm/testhello.py
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FileEntry.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StringTable.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
Labels: oca-signed

#2743 Fall back to copying the image heap when it cannot be found/opened.
  substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapOptions.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxImageHeapProvider.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/c/function/CEntryPointErrors.java
Labels: oracle-emp

#2746 [GR-25507] Use unnamed semaphore for cSunMiscSignal on Linux.
  substratevm/src/com.oracle.svm.native.libchelper/src/cSunMiscSignal.c
Labels: oracle-emp

#2738 Fix code that assumes suites are under a vcs repository
  .mx_vcs_repo
  .travis.yml
  compiler/mx.compiler/mx_compiler.py
  compiler/mx.compiler/suite.py
  sdk/mx.sdk/mx_sdk.py
  sdk/mx.sdk/mx_sdk_vm_impl.py
  sdk/mx.sdk/suite.py
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/mx.substratevm/suite.py
Labels: oca-signed

#2728 ClassValue substitution: Fix computeValue usage
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaLangSubstitutions.java
Labels: oca-signed

#2752 Remove jdk, graal, and src subdirectories from sources cache
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FileEntry.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceCache.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceCacheType.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
Labels: oca-signed

#2749 [GR-25560] Allow optional CodeObserver installation.
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/code/InstalledCodeObserverSupport.java
Labels: oracle-emp

#2349 Github action for testing latest quarkus `master` with latest graal `master`
  .github/workflows/quarkus.yml
Labels: oca-signed, quarkus

#2766 Fixing AArch64 emitCompare and zr/sp issues
  compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64Assembler.java
  compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
  compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LIRGenerator.java
  compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ControlFlow.java
Labels: oracle-emp

#2773 [GR-24417] Generate clean query code.
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/PosixDirectives.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/CAnnotationProcessor.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CCompilerInvoker.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CSourceCodeWriter.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/QueryCodeWriter.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeBootImage.java
Labels: oracle-emp

#2614 Prints JDK build number along with java.version
  substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
Labels: oca-signed

#2813 Replace getdtablesize with sysconf(_SC_OPEN_MAX)
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixSubstrateOperatingSystemMXBean.java
  substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/headers/Unistd.java
Labels: oca-signed
