Repository oracle/graal, pull requests merged in 2020-11, with the labels that each got.

#2953 Fixed typo in conditions
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SystemPropertiesSupport.java
  substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
Labels: oracle-emp

#2952 Fix some warnings in Sulong
  sulong/projects/com.oracle.truffle.llvm.libraries.native/src/posix.c
Labels: llvm, oca-signed

#2966 Do not use CLibrary annotations from inactive @CContexts
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/NativeLibraries.java
  substratevm/src/com.oracle.svm.truffle.nfi/src/com/oracle/svm/truffle/nfi/libffi/LibFFIHeaderDirectives.java
Labels: oracle-emp

#2964 Make `buildArgs` a list to allow reusability from parent POMs
  substratevm/NativeImageMavenPlugin.md
  substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java
Labels: enhancement, oca-signed

#2976 Remove experimental native-image-maven-plugin vanilla JVMCI support.
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/src/native-image-maven-plugin-test/template-pom.xml
  substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java
  substratevm/src/native-image-maven-plugin/template-pom.xml
Labels: oracle-emp

#2886 [CI] Get Quarkus latest version from maven repo metadata
  .github/workflows/quarkus.yml
Labels: accept, oca-signed

#2181 AArch64: Conditionally use barriers for atomic operations.
  compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64MacroAssembler.java
  compiler/src/org.graalvm.compiler.core.aarch64/src/org/graalvm/compiler/core/aarch64/AArch64LIRGenerator.java
  compiler/src/org.graalvm.compiler.core.amd64/src/org/graalvm/compiler/core/amd64/AMD64LIRGenerator.java
  compiler/src/org.graalvm.compiler.core.sparc/src/org/graalvm/compiler/core/sparc/SPARCNodeMatchRules.java
  compiler/src/org.graalvm.compiler.hotspot.sparc/src/org/graalvm/compiler/hotspot/sparc/SPARCHotSpotLIRGenerator.java
  compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64AtomicMove.java
  compiler/src/org.graalvm.compiler.lir/src/org/graalvm/compiler/lir/gen/LIRGeneratorTool.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/java/LogicCompareAndSwapNode.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/java/ValueCompareAndSwapNode.java
  substratevm/src/com.oracle.svm.core.graal.llvm/src/com/oracle/svm/core/graal/llvm/LLVMGenerator.java
Labels: compiler, oca-signed

#2861 Graal part of JDK-8253015: Aarch64: Move linux code out from generic CPU feature detection
  compiler/src/org.graalvm.compiler.hotspot.aarch64/src/org/graalvm/compiler/hotspot/aarch64/AArch64HotSpotLIRGenerator.java
  compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
Labels: oca-signed

#2364 Apply trapping nullcheck to the uncompressed target for compressed po…
  compiler/src/org.graalvm.compiler.core.common/src/org/graalvm/compiler/core/common/type/AbstractPointerStamp.java
  compiler/src/org.graalvm.compiler.core/src/org/graalvm/compiler/core/phases/LowTier.java
  compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/AddressLoweringHotSpotSuitesProvider.java
  compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/nodes/type/KlassPointerStamp.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/extended/NullCheckNode.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/memory/address/OffsetAddressNode.java
  compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/type/NarrowOopStamp.java
  compiler/src/org.graalvm.compiler.phases.common/src/org/graalvm/compiler/phases/common/UseTrappingNullChecksPhase.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
Labels: oca-signed

#2996 update to jvmci-21.0-b01 and switch to GH actions
  .github/workflows/main.yml
  .travis.yml
  common.json
  compiler/ci_common/gate_tasks.hocon
  vm/ci_common/common.hocon
Labels: oca-signed

#2987 Migrate to GH actions
  .github/workflows/main.yml
  .travis.yml
Labels: oca-signed

#3009 Fix broken links to document on build configuration
  substratevm/DynamicProxy.md
  substratevm/JNI.md
  substratevm/Limitations.md
  substratevm/Reflection.md
  substratevm/Resources.md
  substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/NativeImageAgent.java
  substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/target/Target_jdk_internal_misc_Unsafe_Reflection.java
Labels: documentation

#3026 [docs] Add recent publications
  docs/Publications.md
Labels: oca-signed

#2997 [CI] Update Quarkus nightly builds to work with Quarkus 1.10.0.Final
  .github/workflows/main.yml
  .github/workflows/quarkus.yml
Labels: oca-signed
