Repository oracle/graal, pull requests merged in 2021-06, with the labels that each got.

#3468 Only scan for resources in jar if really a jar #3467
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ResourcesFeature.java
Labels: oca-signed

#3473 Trace removed security providers
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/SecurityServicesFeature.java
Labels: oracle-emp

#3453 Parse clang version correctly even when it contains dashes
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CCompilerInvoker.java
Labels: oca-signed

#3478 Fix github actions failures.
  .github/workflows/main.yml
  common.json
  vm/ci_includes/vm.hocon
Labels: oracle-emp

#3504 Support predefinition of classes with subtype and outer class relationships.
  sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/RuntimeClassInitialization.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/hub/ClassForNameSupport.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/hub/DynamicHub.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/hub/DynamicHubCompanion.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/hub/PredefinedClassesSupport.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/util/LazyFinalReference.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ClassPredefinitionFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/snippets/ReflectionPlugins.java
Labels: native-image, oracle-emp

#3419 Use method entries instead of primary ranges for method DIE generation
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/BasicProgbitsSectionImpl.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/ObjectFile.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/StringSectionImpl.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MethodEntry.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StructureTypeEntry.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/ELFProgbitsSection.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/ELFUserDefinedSection.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/macho/MachORegularSection.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/macho/MachOUserDefinedSection.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffProgbitsSection.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffRelocationTable.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/pecoff/PECoffUserDefinedSection.java
Labels: oca-signed

#3488 Fall back to getMetaspacePointer() in JfrEventSubstitution
  substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrEventSubstitution.java
Labels: oca-signed
