Repository oracle/graal, pull requests merged in 2021-02, with the labels that each got.

#3177 [GR-29051] Remove obsolete parts of SerializationFeature.
  substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/BreakpointInterceptor.java
  substratevm/src/com.oracle.svm.agent/src/com/oracle/svm/agent/NativeImageAgent.java
  substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/ConfigurationSet.java
  substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/config/SerializationConfiguration.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/SerializationConfigurationParser.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/doc-files/SerializationConfigurationFilesHelp.txt
  substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/serialize/hosted/SerializationFeature.java
  substratevm/src/com.oracle.svm.util/src/com/oracle/svm/util/SerializationChecksumCalculator.java
Labels: oracle-emp

#3068 make awt invocation plugin conditional on linux os
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/snippets/SubstrateGraphBuilderPlugins.java
Labels: oca-signed

#3205 Fix DW_AT_byte_size of DW_TAG_pointer for direct reference access
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/AbstractBootImage.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeBootImage.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
Labels: bug, oracle-emp

#3206 Run debuginfotest with and without SpawnIsolates
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/mx.substratevm/testhello.py
Labels: oca-signed

#3207 Omit DebugLineInfo originating from inlined methods for now
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateOptions.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
Labels: oracle-emp

#3152 Print TraceClassInitialization without error
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/agent/NativeImageBytecodeInstrumentationAgent.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ConfigurableClassInitialization.java
Labels: oca-signed

#3179 Add exclude-config option
  substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
  substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
Labels: oca-signed

#3229 Fix native-image-agent-library macro build with JDK 11.0.11 EA
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDK11_0_10OrEarlier.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDK11_0_11OrLater.java
  substratevm/src/com.oracle.svm.methodhandles/src/com/oracle/svm/methodhandles/Target_java_lang_invoke_MethodHandles_Lookup.java
Labels: oca-signed
