Repository oracle/graal, pull requests merged in 2021-11, with the labels that each got.

#3981 Replace jdk8 github gates with jdk17 ones
  .github/workflows/main.yml
  substratevm/mx.substratevm/testhello.py
Labels: oca-signed

#3680 Register String(byte[]) constructor for runtime JNI access
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationJava.java
Labels: oca-signed, quarkus

#4000 Fix: finagle-chirper and finagle-http benchmarks on renaissance 0.13.0.
  java-benchmarks/mx.java-benchmarks/mx_java_benchmarks.py
  substratevm/src/com.oracle.svm.configure/src/com/oracle/svm/configure/trace/AccessAdvisor.java
  vm/mx.vm/mx_vm_benchmark.py
Labels: oca-signed

#4051 [GR-21865] Introduce copy-on-write image heap provider on Windows.
  substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/AbstractImageHeapLayouter.java
  substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsImageHeapProvider.java
  substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsUtils.java
  substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsVirtualMemoryProvider.java
  substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/headers/FileAPI.java
  substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/headers/LibC.java
  substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/headers/MemoryAPI.java
  substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/headers/WinBase.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/AbstractCopyingImageHeapProvider.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageViaCC.java
Labels: oracle-emp

#4042 [GR-35274] Restore missing param type names in method signatures in debug log statements
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
Labels: oca-signed

#3991 [GR-34444] Replicate hosted module relations in runtime boot module layer
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/src/com.oracle.svm.core.jdk11/src/com/oracle/svm/core/jdk11/Target_java_lang_Module_JDK11OrLater.java
  substratevm/src/com.oracle.svm.hosted.jdk11/src/com/oracle/svm/hosted/ModuleLayerFeature.java
  substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrFeature.java
  substratevm/src/native-image-module-tests/hello.app/src/main/java/hello/Main.java
Labels: oca-signed

#4046 [GR-35277] Fix merging of debug info subranges and make debuginfotest more resiliant to JDK changes
  substratevm/mx.substratevm/testhello.py
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
  substratevm/src/com.oracle.svm.test/src/hello/Hello.java
Labels: oca-signed
