Repository oracle/graal, pull requests merged in 2022-11, with the labels that each got.

#4868 Handle control flow split of WithExceptionNode nodes when replacing nodes
  compiler/src/org.graalvm.compiler.virtual/src/org/graalvm/compiler/virtual/phases/ea/GraphEffectList.java
Labels: OCA Verified

#5436 [GR-42531] Debug info memory footprint improvements
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
  substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfSectionImpl.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
Labels: performance, enhancement, native-image-debuginfo, OCA Verified

#5390 [GR-42460] Add support for CgroupMetrics.getTotalMemory0
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/CgroupMetricsJDK.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/HasGetTotalMemorySize0.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_internal_platform_CgroupMetrics.java
Labels: native-image, OCA Verified

#5332 [Backport][22.3] Only require libmanagement_ext if it's actually needed.
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationManagementExt.java
Labels: OCA Verified
