Repository oracle/graal, pull requests merged in 2022-06, with the labels that each got.

#4482 Convert Java byte array to CCharPointerHolder
  sdk/src/org.graalvm.nativeimage/snapshot.sigtest
  sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/c/type/CTypeConversion.java
  sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/impl/CTypeConversionSupport.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/c/CTypeConversionSupportImpl.java
Labels: oca-signed

#4633 Removes import needed by javadoc to eliminate build-time dependency
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/meta/ObjectConstantEquality.java
Labels: oca-signed, native-image

#4635 [GR-39065] Enables native-image script to handle module path with spaces.
  sdk/mx.sdk/mx_sdk_vm_impl.py
Labels: oca-signed, native-image

#4638 [GR-39144] Update reference manual now debug info includes local vars
  docs/reference-manual/native-image/DebugInfo.md
Labels: oca-signed

#4657 [GR-39313] Avoid NPEs in includeAnnotation when annotationValue is null
  substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/hosted/ReflectionDataBuilder.java
Labels: bug, oca-signed, native-image
