Repository oracle/graal, pull requests merged in 2022-03, with the labels that each got.

#4327 [GR-37154] Fix handling of resources with trailing slashes
  substratevm/mx.substratevm/suite.py
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Resources.java
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/resources/ResourceURLConnection.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/NativeImageResourceFileSystemProviderTest.java
  substratevm/src/com.oracle.svm.test/src/resources/.mxkeep
Labels: oca-signed

#4237 Clarify documentation for @ExplodeLoop
  truffle/src/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/ExplodeLoop.java
Labels: oca-signed, truffle, documentation

#4366 Make CSV link relative instead of absolute
  substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/reports/CallTreePrinter.java
Labels: native-image

#4155 Add SIMD version of String.compareTo intrinsic for AArch64
  compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64ASIMDAssembler.java
  compiler/src/org.graalvm.compiler.asm.aarch64/src/org/graalvm/compiler/asm/aarch64/AArch64ASIMDMacroAssembler.java
  compiler/src/org.graalvm.compiler.lir.aarch64/src/org/graalvm/compiler/lir/aarch64/AArch64ArrayCompareToOp.java
Labels: oca-signed

#4435 JFR: Fix JFR large events
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrNativeEventWriter.java
Labels: oca-signed
