Repository oracle/graal, pull requests merged in 2023-11, with the labels that each got.

#6985 [GR-49816] Throw exception for null pointers passed to RuntimeJNIAccess / RuntimeReflection register methods
  substratevm/mx.substratevm/mx_substratevm.py
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ConditionalConfigurationRegistry.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jni/JNIAccessFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/ReflectionRegistrationTest.java
Labels: OCA Verified, redhat-interest

#7256 Use calling convention to derive incoming param register and stack slot locations
  substratevm/mx.substratevm/testhello.py
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoFeature.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProviderBase.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/debug/CStructTests.java
  substratevm/src/com.oracle.svm.test/src/hello/Hello.java
Labels: native-image-debuginfo, OCA Verified, redhat-interest

#7671 Fixes issue-7652 for epsilon gc [master]
  substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/HeapImpl.java
Labels: OCA Verified

#7663 Add a `Pause` prefix to the serial GC log entries
  substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/GCImpl.java
Labels: OCA Verified

#7736 Synchronize accesses to reachability handlers
  substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ReachabilityHandlerFeature.java
Labels: OCA Verified, redhat-interest
