Repository oracle/graal, pull requests merged in 2024-01, with the labels that each got.

#8089 [GR-51139] Add islisp entry to Languages.md
  truffle/docs/Languages.md
Labels: OCA Required

#7998 [GR-51017] Use JDK 17 for building Quarkus
  .github/workflows/quarkus.yml
Labels: OCA Verified

#7308 Fix typo in Shape.newBuilder().layout()
  truffle/docs/DynamicObjectModel.md
Labels: documentation, OCA Verified

#8137 [GR-51276] Use latest labsjdk in Quarkus github workflow
  .github/workflows/quarkus.yml
Labels: OCA Verified

#5383 Fix typo in toc_group
  truffle/docs/LanguageTutorial.md
Labels: OCA Verified
