Repository oracle/graal, pull requests merged in 2025-08, with the labels that each got.

#11819 [GR-68862] Github: [Native Image] [Windows] Required environment variable names use case-sensitive compare on Windows
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/util/EnvVariableUtils.java
Labels: OCA Verified, redhat-interest

#11769 [GR-69121] Skip emission of internal JFR ThreadPark events
  substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/events/ThreadParkEvent.java
  substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/jfr/TestOmitInternalParkEvents.java
Labels: native-image, OCA Verified, redhat-interest, native-image-jfr

#9809 Fix typos in Markdown files
  compiler/docs/Debugging.md
  docs/graalvm-as-a-platform/implement-language.md
  docs/reference-manual/llvm/Compiling.md
  docs/reference-manual/native-image/DebugInfo.md
  docs/tools/insight/Insight-Manual.md
  docs/tools/insight/README.md
  espresso/docs/continuations.md
  espresso/docs/how-espresso-works.md
  sdk/CHANGELOG.md
  sdk/mx.sdk/vm/windows.md
  substratevm/CHANGELOG.md
  substratevm/docs/module-system/ModuleSystemSupportRuntime.md
  sulong/docs/contributor/INTEROP.md
  tools/CHANGELOG.md
  tools/docs/Insight.md
  truffle/CHANGELOG.md
  truffle/docs/DSLNodeObjectInlining.md
  truffle/docs/Exit.md
  truffle/docs/Languages.md
  truffle/docs/NFI.md
  truffle/docs/Optimizing.md
  truffle/docs/Options.md
  truffle/docs/Profiling.md
  truffle/docs/Safepoints.md
  truffle/docs/splitting/ReportingPolymorphism.md
  visualizer/Modules.md
Labels: OCA Verified
